### ISSUE TITLE
Able to have latent calls?

### ISSUE THREAD

**Issue by iUltimateLP** [rdeioris/LuaMachine#18]
Hey, I want to use this to implement robots in my puzzle game. 

An example Lua code would look like this:
```lua
robot.walkForward()
robot.turnLeft()
robot.walkForward()
```
As you can see, I'd need the calls to be "blocking", or non-returning until the robot fully finished moving. Is that possible? Thanks!

**Comment by rdeioris** [comment]
@iUltimateLP you can use coroutine. Start by wrapping (you have various ways) the sequence of moves in a coroutine:

```lua
local robot = {}

function robot.actions()
  -- get the currently running coroutine
  coro = coroutine.running()
  print('actions!')
  -- pass the 'coro' to the blueprint to allow resuming later
  robot_up(coro)
  print('first step done')
  -- this yield will suspend the coroutine, it will be resumed by the previous blueprint
  coroutine.yield()

  -- and again...
  robot_up(coro)
  print('second step done')
  coroutine.yield()

  -- and again...
  robot_up(coro)
  print('end of coroutine')
end

return robot
```

the robot_up function is a blueprint event:

![immagine](https://user-images.githubusercontent.com/2234592/96337344-c6afbc80-1086-11eb-8c9d-7d9e4f5a76c0.png)

you can directly spawn coroutine from blueprint/c++ (otherwise just use lua):

![immagine](https://user-images.githubusercontent.com/2234592/96337384-0c6c8500-1087-11eb-97c8-9074454ae60e.png)

**Comment by iUltimateLP** [comment]
Great, thanks for your detailed answer!
