### ISSUE TITLE
Character's functions from state

### ISSUE THREAD

**Issue by Nogitsu** [rdeioris/LuaMachine#2]
Hi, I am trying to call functions of a Character from a Widget run, I'm getting my Character from my Lua State but when I try to call Characters function, nothing happens, and nothing in my console..

In game:
![image](https://user-images.githubusercontent.com/25884866/52011292-d57fc580-24d7-11e9-824c-299b0a2b9a4d.png)

Commands + when pressing run:
![image](https://user-images.githubusercontent.com/25884866/52011323-ee887680-24d7-11e9-8fa7-82dc73f1b292.png)

GetPlayer()
![image](https://user-images.githubusercontent.com/25884866/52011349-fcd69280-24d7-11e9-968d-75c777283099.png)

Player's Lua Component's Content
![image](https://user-images.githubusercontent.com/25884866/52011422-30b1b800-24d8-11e9-9195-36ad79d361db.png)

**Comment by rdeioris** [comment]
Hi @Nogitsu , thanks for the great report. Your issue is related to a non-updated docs paragraph about LuaComponent usage (just fixed it). In the latest releases i have removed any form of 'automagic' from the plugin, so when you return an Actor (even if it has a LuaComponent attached), the actor itself will be received by Lua (as userdata):

https://github.com/rdeioris/LuaMachine/blob/master/Docs/LuaComponent.md#luacomponent-interactions

This allows a more versatile approach for advanced extensions (like the reflection described here: https://github.com/rdeioris/LuaMachine/blob/master/Tutorials/ReflectionShell.md)

I have just released a new update including various shortcuts for retrieving the LuaComponent from an Actor as a LuaValue.

If you want to fix your blueprint without updating, just call GetComponentByClass after the GetPlayerPawn, and encapsulate the result in a lua value.

Let me know if it works for you

**Comment by rdeioris** [comment]
Hi again, the plugin has been approved for the Marketplace, so i need to check if i can make a binary release here. (older binary releases are prtty outdated)

**Comment by Nogitsu** [comment]
Approved but not published ?
![image](https://user-images.githubusercontent.com/25884866/52070860-17654600-2582-11e9-879f-6489f994edef.png)

**Comment by Nogitsu** [comment]
The binary release now works, thanks 😃
